# PR Checker

name: Beneficiary Reporting Validation - PR Checker

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Configure Node version and registry
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install Dependencies
        run: npm ci
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Run Tests
        run: npm run test:cov
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Run Build Test
        run: npm run build
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
